import { Inter } from "@next/font/google"
import "@/styles/reset.css"
import "@/styles/global.css"

import Header from "@/containers/header"
import Footer from "@/containers/footer"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const interFontFamily = Inter({
  subsets: ["latin"],
})

export default function RootLayout({ children }) {
  return (
    <html lang="tr" className={interFontFamily.className}>
      <body className="container">
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
